### ISSUE TITLE
required field behaviour for single select lists differs from trackers 

### ISSUE THREAD

**Issue by okosel** [voko/teamforge-flexdocversions#3]
the behaviour for required fields in single select lists should be consistent for flex fields and tracker single select lists. this fact should also be considered for multi select lists.

**Comment by voko** [comment]
Teamforge 16.3 behaviour for required fields.

## text field
* required field has to have a default value

## single select field
If required is set:
* a default value has to be selected
* None (i.e. NIL/empty) can be set as default

**Comment by voko** [comment]
moved to [teamforge-flexadmin #9](https://github.com/voko/teamforge-flexadmin/issues/9)
